#!/usr/bin/env python3
"""Render the agent guide's tool inventory without importing Spine or the MCP extra."""

from __future__ import annotations

import argparse
import ast
import difflib
import re
from pathlib import Path

START = "<!-- BEGIN GENERATED MCP TOOLS -->"
END = "<!-- END GENERATED MCP TOOLS -->"


def assignments(tree: ast.Module) -> dict[str, ast.expr]:
    result = {}
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    result[target.id] = node.value
        elif isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name) and node.value:
            result[node.target.id] = node.value
    return result


def names(node: ast.expr) -> dict[str, str]:
    if not isinstance(node, ast.Dict):
        raise ValueError("Expected a literal registry dictionary")
    result = {}
    for key, value in zip(node.keys, node.values, strict=True):
        if not isinstance(key, ast.Constant) or not isinstance(key.value, str):
            raise ValueError("Registry keys must be literal tool names")
        if not isinstance(value, ast.Name) or key.value in result:
            raise ValueError(f"Invalid or duplicate registry entry: {key.value}")
        result[key.value] = value.id
    return result


def render(root: Path) -> str:
    plugin = root / "src/orchestrator/plugin"
    tree = ast.parse((plugin / "server.py").read_text())
    values = assignments(tree)
    outputs = names(assignments(ast.parse((plugin / "outputs.py").read_text()))["OUTPUTS"])
    tiers = names(values["_TIER"])
    auth = assignments(ast.parse((plugin / "auth.py").read_text()))
    tools_node = values["_TOOLS"]
    if not isinstance(tools_node, ast.Tuple) or not all(isinstance(n, ast.Name) for n in tools_node.elts):
        raise ValueError("_TOOLS must be a tuple of tool functions")
    tools = [n.id for n in tools_node.elts if isinstance(n, ast.Name)]
    if len(set(tools)) != len(tools) or set(tools) != set(outputs) or set(tools) != set(tiers):
        raise ValueError("_TOOLS, _TIER and OUTPUTS must contain exactly the same unique names")
    functions = {n.name: n for n in tree.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))}
    lines = [
        START,
        "<!-- Generated by scripts/mcp-tools.py; edit registration metadata, not this table. -->",
        "",
        "| Tool | What it does | Read-only hint | HTTP scope | Output schema |",
        "|---|---|---|---|---|",
    ]
    for name in tools:
        doc = ast.get_docstring(functions[name])
        if not doc:
            raise ValueError(f"Missing tool description: {name}")
        summary = " ".join(doc.split("\n\n", 1)[0].split())
        summary = summary.replace("``", "`").replace("|", "&#124;")
        tier = values[tiers[name]]
        if not isinstance(tier, ast.Call) or not isinstance(tier.func, ast.Name):
            raise ValueError(f"Expected a Tier declaration for {name}")
        if tier.func.id != "Tier":
            raise ValueError(f"Expected a Tier declaration for {name}")
        fields = {k.arg: k.value for k in tier.keywords}
        read_only = ast.literal_eval(fields["read_only"])
        scope = fields["scope"]
        if not isinstance(read_only, bool) or not isinstance(scope, ast.Name):
            raise ValueError(f"Unsupported tier metadata for {name}")
        # Scope constants are imported from auth.py; resolve their literal values there.
        scope_value = ast.literal_eval(auth[scope.id])
        lines.append(
            f"| `{name}` | {summary} | {'yes' if read_only else 'no'} | `{scope_value}` | `{outputs[name]}` |"
        )
    lines.extend(["", END])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed table is stale")
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    guide = args.root / "AGENT_GUIDE.md"
    try:
        original = guide.read_text()
        if original.count(START) != 1 or original.count(END) != 1:
            raise ValueError("AGENT_GUIDE.md needs exactly one generated MCP tool block")
        expected, count = re.subn(
            re.escape(START) + r".*?" + re.escape(END),
            lambda _: render(args.root),
            original,
            flags=re.S,
        )
        if count != 1:
            raise ValueError("Generated MCP tool markers are out of order")
    except (OSError, ValueError, KeyError, SyntaxError) as error:
        parser.exit(1, f"MCP tool table: {error}\n")
    if original == expected:
        print("MCP tool table is current.")
        return 0
    if args.check:
        print("MCP tool table is stale; run: uv run --frozen python scripts/mcp-tools.py")
        print("".join(difflib.unified_diff(original.splitlines(True), expected.splitlines(True))))
        return 1
    guide.write_text(expected)
    print("Updated AGENT_GUIDE.md from the registered tools, tiers and output schemas.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
